CREATE TABLE `dev_raw.workable_postings_incoming` (
    id STRING NOT NULL OPTIONS(description="Workable's job shortcode. NOT unique in this table: the same id appears once per landed file that contained it. The MERGE deduplicates on it, keeping the row with the newest landed_at."),
    title STRING OPTIONS(description="Job title as published, from the list entry's 'title'. Not cleaned."),
    url STRING OPTIONS(description="Public URL of the posting, from the list entry's 'url'. The apply link ('application_url') is this URL plus '/apply' and is not stored."),
    city STRING OPTIONS(description="City as published, from the list entry's 'city'. Free text."),
    region STRING OPTIONS(description="Region/state as published, from the list entry's 'state' (renamed: 'state' in the detail response means the posting's status, e.g. 'published')."),
    country STRING OPTIONS(description="Country NAME as published, from the list entry's 'country', e.g. 'United States'. See country_code for the ISO form."),
    country_code STRING OPTIONS(description="ISO-3166 alpha-2 code of the first listed location, from 'locations[0].countryCode', e.g. 'US'. The same payload gives the country as a name AND as a code - both kept; further locations stay in raw."),
    telecommuting BOOL OPTIONS(description="Remote flag from the LIST response ('telecommuting'). Workable expresses remoteness three times across its two payloads: this, plus 'workplace' and 'remote' in the detail. The list flag is the only one available for every job every night."),
    department STRING OPTIONS(description="Department as published, from the list entry's 'department'. Often null (and the detail response has it as an array, usually empty)."),
    employment_type STRING OPTIONS(description="Employment type as published, from the list entry's 'employment_type', e.g. 'Full-time'. Workable's own spelling, NOT normalised: Lever says 'Full-Time', Ashby 'FullTime'. Mapping happens downstream."),
    education STRING OPTIONS(description="Required education as published, from the list entry's 'education', e.g. Bachelor's Degree. One of four taxonomy fields only Workable (and SmartRecruiters) provide; empty strings are stored as NULL."),
    experience STRING OPTIONS(description="Seniority as published, from the list entry's 'experience', e.g. 'Director', 'Mid-Senior level'. The only seniority signal among the sources loaded so far."),
    industry STRING OPTIONS(description="Industry as published, from the list entry's 'industry', e.g. 'Electrical/Electronic Manufacturing'."),
    job_function STRING OPTIONS(description="Job function as published, from the list entry's 'function' (renamed: 'function' reads like a SQL keyword)."),
    published_on DATE OPTIONS(description="Publication DATE from the list entry's 'published_on' ('2026-09-01'). Date only, no time: stored as DATE rather than a fabricated midnight timestamp. (The detail's 'published' is the same day at 00:00Z.)"),
    workplace STRING OPTIONS(description="Workplace as published, from the DETAIL response's 'workplace': 'on_site', 'hybrid', 'remote'. Richer than telecommuting, but only for jobs whose detail has been fetched."),
    language STRING OPTIONS(description="Posting language from the DETAIL response's 'language', e.g. 'en'."),
    content STRING OPTIONS(description="Job description from the DETAIL response's 'description'. HTML, stored unparsed. NULL until the job's detail has been fetched (see detail_fetched_at). Workable splits the text in three - this, 'requirements', 'benefits' - each kept as its own column, as other sources' sections are."),
    requirements STRING OPTIONS(description="Requirements section from the DETAIL response's 'requirements'. HTML."),
    benefits STRING OPTIONS(description="Benefits section from the DETAIL response's 'benefits'. HTML."),
    salary_min NUMERIC OPTIONS(description="Lower salary bound from the DETAIL response's 'salary_from' (flat fields here; Lever and Ashby nest salary in an object). NUMERIC: money is never a float. Absent from most postings."),
    salary_max NUMERIC OPTIONS(description="Upper salary bound from the DETAIL response's 'salary_to'."),
    salary_currency STRING OPTIONS(description="Currency from the DETAIL response's 'salary_currency_iso_code', ISO-4217."),
    salary_frequency STRING OPTIONS(description="Period the salary refers to, from the DETAIL response's 'salary_frequency', e.g. 'year'. Lever/Ashby say 'interval', Recruitee 'period'."),
    raw STRING NOT NULL OPTIONS(description="The job's entries from Workable's LIST response, as a JSON ARRAY. The list repeats a job once per location (one board: 1,905 entries for 318 jobs), each entry carrying only its own location; the row takes city/region/country from the first entry, and this array keeps every entry so no location is lost. Also holds list-only fields not flattened above (e.g. 'application_url', 'created_at')."),
    raw_detail STRING OPTIONS(description="The job's DETAIL response, as JSON text. NULL until fetched. Fetched once per job (and again after 30 days), not every night - see detail_fetched_at."),
    has_detail BOOL NOT NULL OPTIONS(description="Whether this row's file carried the job's DETAIL response (fetched this run). FALSE means the detail columns are NULL because nothing was fetched, not because the source left them empty: the MERGE uses this flag to keep the final table's existing detail values."),
    company_slug STRING OPTIONS(description="The board this row's file was fetched from (the slug in the landed file's path). Stamped by the loader; the MERGE copies it to the raw table. See the raw table's company_slug."),
    first_seen_at TIMESTAMP NOT NULL OPTIONS(description="Landing time of the file this row came from. In staging it equals landed_at and last_seen_at; the MERGE decides what reaches the final table, where it means something different (the FIRST sighting ever)."),
    last_seen_at TIMESTAMP NOT NULL OPTIONS(description="Landing time of the file this row came from. Compared against the final table's last_seen_at by the MERGE, so older files cannot overwrite newer rows."),
    landed_at TIMESTAMP NOT NULL OPTIONS(description="When the GCS file this row came from was created (the object's time_created). Ties every row back to one landed file: used to deduplicate (newest file wins per id) and by the C2 check to prove staging was rebuilt from this day's files."),
    PRIMARY KEY (id, landed_at) NOT ENFORCED
)
OPTIONS(description="One row per Workable job posting PER LANDED FILE. Load-mechanics staging only: fully replaced (WRITE_TRUNCATE) on every run of the workable_ingestion DAG and then MERGEd into dev_raw.workable_postings. Rows whose file carried no detail response have has_detail = FALSE and NULL detail columns. Not partitioned: one run's data, always scanned whole. Not the dbt staging layer - unrelated concept, same word.");
