CREATE TABLE `dev_raw.teamtailor_postings` (
    id STRING NOT NULL OPTIONS(description="Teamtailor's posting identifier, from the RSS item's 'guid', a UUID string. The only id in the payload (a numeric id appears inside 'link' but is not a field). Unique per row: this is the merge key."),
    title STRING OPTIONS(description="Job title as published, from the item's 'title'. Not cleaned."),
    url STRING OPTIONS(description="Public URL of the posting, from the item's 'link'. Often on the company's own careers domain rather than teamtailor.com."),
    location STRING OPTIONS(description="Name of ONE location of the posting, from 'tt:locations/tt:location/tt:name'. A posting can list several (8.5% list 2 to 13; some list none): the loader stores a Brazilian location if the posting has one, otherwise the first. This choice is a product preference applied at load time; the full list stays in 'raw'."),
    city STRING OPTIONS(description="City of the same chosen location, from 'tt:city'. Free text, not normalised."),
    country STRING OPTIONS(description="Country of the same chosen location, from 'tt:country'. A country NAME in English or the local language (e.g. 'Norway', 'Brazil', once 'Brasil'), not an ISO code: another vocabulary for the downstream country mapping."),
    remote_status STRING OPTIONS(description="Remoteness as published, from the item's 'remoteStatus', stored verbatim: 'none', 'onsite', 'hybrid', 'fully', 'temporary'. CAUTION: 'none' (61% of postings) is ambiguous - it behaves like 'remote not offered' (0.3% of such titles mention remote, vs 17% for 'fully'), but 'onsite' exists as a separate value, so it may also mean 'never set'. Interpreting it is a downstream decision."),
    department STRING OPTIONS(description="Department as published, from 'tt:department'. The level ABOVE role; both are kept, as ashby_postings keeps department and team."),
    role STRING OPTIONS(description="Role as published, from 'tt:role'. The level BELOW department. Often empty."),
    content STRING OPTIONS(description="Full job description, from the item's 'description'. HTML (the XML escaping is undone by the parser, so this is ordinary HTML, not entity-escaped). Checked to be the full posting, not an RSS summary: it ends where the job page's text ends."),
    published_at TIMESTAMP OPTIONS(description="When the posting was published, from the item's 'pubDate'. The source sends RFC-822 ('Wed, 30 Sep 2026 09:36:12 +0200'), which BigQuery cannot parse, so the loader converts it, keeping the offset. A source timestamp, not a pipeline one."),
    raw STRING NOT NULL OPTIONS(description="The complete original <item> element for this posting, as XML text (re-serialised by the parser: same content and tt: prefix, but not byte-identical to the feed - whitespace and escaping may differ; the exact bytes are in GCS) - NOT JSON, unlike every other *_postings table, because the source is RSS and converting it would add choices the source never made. Holds everything not flattened above, notably the full 'tt:locations' list. BigQuery's JSON functions do not apply; parse it in a staging model if needed. The whole feed is kept as an .xml file in GCS."),
    first_seen_at TIMESTAMP NOT NULL OPTIONS(description="When this job was FIRST seen in a landed file (the GCS object's creation time), not when the loader ran. Only ever moves earlier: re-loading an older day corrects it."),
    last_seen_at TIMESTAMP NOT NULL OPTIONS(description="When this job was MOST RECENTLY seen in a landed file (the GCS object's creation time), not when the loader ran. Only ever moves later: older data cannot overwrite a newer row. Teamtailor publishes no 'updated_at', so this is the only freshness signal."),
    PRIMARY KEY (id) NOT ENFORCED
)
OPTIONS(description="One row per Teamtailor job posting, holding its current state (not one row per ingestion). Raw layer: values are as published by the source, flattened but not cleaned or normalised, and kept under Teamtailor's own vocabulary. The source is an RSS feed, so 'raw' holds XML, not JSON. Teamtailor sends no salary, employment type, updated_at or per-posting company name. Loaded daily by the teamtailor_ingestion DAG, which replaces dev_raw.teamtailor_postings_incoming and MERGEs it here on id, newest landed file wins. Full history of every feed is kept as files in GCS, not in this table.");
