CREATE TABLE `dev_raw.ashby_postings` (
    id STRING NOT NULL OPTIONS(description="Ashby's own posting id, a UUID string ('id'). Unique per row: this is the merge key. STRING, not INT64 as in greenhouse_postings - source id types differ per ATS."),
    title STRING OPTIONS(description="Job title as published, from 'title'. Not cleaned."),
    url STRING OPTIONS(description="Public URL of the posting on the company's Ashby board, from 'jobUrl'. The apply link ('applyUrl') is this URL plus '/application' and is not stored."),
    location STRING OPTIONS(description="Primary location as published, from 'location', a free-text string, e.g. 'Foster City, CA'. Not normalised. A posting may list more: 'secondaryLocations' holds them and is kept only in 'raw', as is the structured 'address' (locality, region, country)."),
    department STRING OPTIONS(description="Department as published, from 'department', e.g. 'Engineering'. The level ABOVE team. Note lever_postings.department holds Lever's team, not a department: the same column name means different things per source until the canonical layer reconciles them."),
    team STRING OPTIONS(description="Team as published, from 'team', e.g. 'Design Engineering & Mobile'. The level BELOW department. Kept alongside 'department' because Ashby publishes both; which one becomes the canonical 'department' is a downstream decision."),
    employment_type STRING OPTIONS(description="Employment type as published, from 'employmentType', e.g. 'FullTime'. Ashby's own spelling, NOT normalised despite the neutral name: Lever says 'Full-Time' and Workable 'Full-time' for the same thing. Mapping to one vocabulary happens downstream."),
    workplace_type STRING OPTIONS(description="Remoteness as published, from 'workplaceType'. Stored verbatim in Ashby's own vocabulary, which differs from Lever's; mapping to the canonical four-value enum happens downstream. Ashby also sends 'isRemote', a lossy boolean summary of this field, which is not stored."),
    country STRING OPTIONS(description="Country as published, from 'address.postalAddress.addressCountry'. Ashby has no top-level country field. Not validated or mapped: observed values are names or alpha-3-like codes (e.g. 'USA'), where Lever sends ISO alpha-2 ('US')."),
    content STRING OPTIONS(description="Full job description as PLAIN TEXT, from 'descriptionPlain'. Unlike greenhouse_postings and lever_postings, whose 'content' is HTML: Ashby provides a text version, so no conversion is needed. The HTML ('descriptionHtml') is kept only in 'raw'."),
    is_listed BOOL OPTIONS(description="Whether the posting is displayed on the public board, from 'isListed'. In practice always true: the public board API only returns listed postings (12,087 of 12,087 on 2026-09-28), so this column never marks a closed role - a stale last_seen_at is the real signal, as for every other source. Kept because it is cheap and would reveal a change in the API's behaviour."),
    salary_min NUMERIC OPTIONS(description="Lower bound of the advertised pay, from the single 'compensation.summaryComponents' entry with compensationType = 'Salary'. Null when there is no such entry, or more than one. CAUTION: Ashby's 'Salary' may be on-target earnings (base + variable bonus), not base pay - see compensation_summary - so it is not directly comparable with lever_postings.salary_min. NUMERIC: money is never stored as a float."),
    salary_max NUMERIC OPTIONS(description="Upper bound of the advertised pay, from the same 'Salary' component's 'maxValue'. Equal to salary_min when a single figure is advertised."),
    salary_currency STRING OPTIONS(description="Currency of the advertised pay, from the same component's 'currencyCode', an ISO-4217 code (e.g. 'USD')."),
    salary_interval STRING OPTIONS(description="Period the pay refers to, from the same component's 'interval', e.g. '1 YEAR'. Stored verbatim, never inferred from the amount; Lever's equivalent is spelled 'per-year-salary', so mapping happens downstream."),
    compensation_summary STRING OPTIONS(description="Human-readable pay summary as published, from 'compensation.compensationTierSummary', e.g. '$86.5K • Base: $51.5K; Variable Bonus: $35K'. The only flattened place where base vs bonus vs equity is visible. Tiers, equity and bonus components stay in 'raw'. Null when the board does not publish compensation."),
    published_at TIMESTAMP OPTIONS(description="When the posting was published, as reported by the source ('publishedAt', ISO-8601 with offset). A source timestamp, not a pipeline one. Ashby publishes no 'updated_at'."),
    raw STRING NOT NULL OPTIONS(description="The complete original API object for this posting, as JSON text. Kept so any field dropped or flattened above - 'descriptionHtml', 'secondaryLocations', 'address', 'compensationTiers', 'isRemote' - can be recovered without re-fetching."),
    first_seen_at TIMESTAMP NOT NULL OPTIONS(description="When this job was FIRST seen in a landed file (the GCS object's creation time), not when the loader ran. Only ever moves earlier: re-loading an older day corrects it."),
    last_seen_at TIMESTAMP NOT NULL OPTIONS(description="When this job was MOST RECENTLY seen in a landed file (the GCS object's creation time), not when the loader ran. Only ever moves later: older data cannot overwrite a newer row. Ashby publishes no 'updated_at', so this is the only freshness signal: 'has this job changed?' cannot be answered from the payload, only 'was it still listed'."),
    PRIMARY KEY (id) NOT ENFORCED
)
OPTIONS(description="One row per Ashby job posting, holding its current state (not one row per ingestion). Raw layer: values are as published by the source, flattened but not cleaned or normalised, and kept under Ashby's own vocabulary where it differs from other sources. Note 'content' is plain text here, HTML in the other sources. Loaded daily by the ashby_ingestion DAG, which replaces dev_raw.ashby_postings_incoming and MERGEs it here on id, newest landed file wins. Full history of every API response is kept as files in GCS, not in this table.");
