CREATE TABLE `dev_raw.teamtailor_postings_incoming` (
    id STRING NOT NULL OPTIONS(description="Teamtailor's posting identifier, from the RSS item's 'guid', a UUID string. NOT unique in this table: the same id appears once per landed file that contained it. The MERGE deduplicates on it, keeping the row with the newest landed_at."),
    title STRING OPTIONS(description="Job title as published, from the item's 'title'. Not cleaned."),
    url STRING OPTIONS(description="Public URL of the posting, from the item's 'link'. Often on the company's own careers domain rather than teamtailor.com."),
    location STRING OPTIONS(description="Name of ONE location of the posting, from 'tt:locations/tt:location/tt:name'. A posting can list several (8.5% list 2 to 13; some list none): the loader stores a Brazilian location if the posting has one, otherwise the first. This choice is a product preference applied at load time; the full list stays in 'raw'."),
    city STRING OPTIONS(description="City of the same chosen location, from 'tt:city'. Free text, not normalised."),
    country STRING OPTIONS(description="Country of the same chosen location, from 'tt:country'. A country NAME in English or the local language (e.g. 'Norway', 'Brazil', once 'Brasil'), not an ISO code: another vocabulary for the downstream country mapping."),
    remote_status STRING OPTIONS(description="Remoteness as published, from the item's 'remoteStatus', stored verbatim: 'none', 'onsite', 'hybrid', 'fully', 'temporary'. CAUTION: 'none' (61% of postings) is ambiguous - it behaves like 'remote not offered' (0.3% of such titles mention remote, vs 17% for 'fully'), but 'onsite' exists as a separate value, so it may also mean 'never set'. Interpreting it is a downstream decision."),
    department STRING OPTIONS(description="Department as published, from 'tt:department'. The level ABOVE role; both are kept, as ashby_postings keeps department and team."),
    role STRING OPTIONS(description="Role as published, from 'tt:role'. The level BELOW department. Often empty."),
    content STRING OPTIONS(description="Full job description, from the item's 'description'. HTML (the XML escaping is undone by the parser, so this is ordinary HTML, not entity-escaped). Checked to be the full posting, not an RSS summary: it ends where the job page's text ends."),
    published_at TIMESTAMP OPTIONS(description="When the posting was published, from the item's 'pubDate'. The source sends RFC-822 ('Wed, 30 Sep 2026 09:36:12 +0200'), which BigQuery cannot parse, so the loader converts it, keeping the offset. A source timestamp, not a pipeline one."),
    raw STRING NOT NULL OPTIONS(description="The complete original <item> element for this posting, as XML text (re-serialised by the parser: same content and tt: prefix, but not byte-identical to the feed - whitespace and escaping may differ; the exact bytes are in GCS) - NOT JSON, unlike every other *_postings table, because the source is RSS and converting it would add choices the source never made. Holds everything not flattened above, notably the full 'tt:locations' list. BigQuery's JSON functions do not apply; parse it in a staging model if needed. The whole feed is kept as an .xml file in GCS."),
    company_slug STRING OPTIONS(description="The board this row's file was fetched from (the slug in the landed file's path). Stamped by the loader; the MERGE copies it to the raw table. See the raw table's company_slug."),
    first_seen_at TIMESTAMP NOT NULL OPTIONS(description="Landing time of the file this row came from. In staging it equals landed_at and last_seen_at; the MERGE decides what reaches the final table, where it means something different (the FIRST sighting ever)."),
    last_seen_at TIMESTAMP NOT NULL OPTIONS(description="Landing time of the file this row came from. Compared against the final table's last_seen_at by the MERGE, so older files cannot overwrite newer rows."),
    landed_at TIMESTAMP NOT NULL OPTIONS(description="When the GCS file this row came from was created (the object's time_created). Ties every row back to one landed file: used to deduplicate (newest file wins per id) and by the C2 check to prove staging was rebuilt from this day's files."),
    PRIMARY KEY (id, landed_at) NOT ENFORCED
)
OPTIONS(description="One row per Teamtailor job posting PER LANDED FILE (so the same id appears once per file that contained it). Load-mechanics staging only: fully replaced (WRITE_TRUNCATE) on every run of the teamtailor_ingestion DAG and then MERGEd into dev_raw.teamtailor_postings. Not partitioned: it holds one run's data, is rebuilt from scratch each time and is always scanned whole by the MERGE, so there is nothing for partition pruning to skip. Not the dbt staging layer - unrelated concept, same word.");
