CREATE TABLE `dev_raw.lever_postings_incoming` (
    id STRING NOT NULL OPTIONS(description="Lever's own posting id, a UUID string ('id'). NOT unique in this table: the same id appears once per landed file that contained it. The MERGE deduplicates on it, keeping the row with the newest landed_at."),
    title STRING OPTIONS(description="Job title as published, from the source field 'text' (Lever's name for the title). Not cleaned."),
    url STRING OPTIONS(description="Public URL of the posting on the company's Lever board, from 'hostedUrl'. The apply link ('applyUrl') is this URL plus '/apply' and is not stored."),
    location STRING OPTIONS(description="Free-text location as published, from 'categories.location', e.g. 'Remote', 'London'. Not normalised. A posting may list several: 'categories.allLocations' holds the full array and is kept only in 'raw'."),
    department STRING OPTIONS(description="Team the posting belongs to, from 'categories.team', e.g. 'Sales'. Named 'department' to match greenhouse_postings; Lever also has an optional 'categories.department' (a level above team) which is NOT stored here and remains in 'raw'."),
    commitment STRING OPTIONS(description="Employment type as published, from 'categories.commitment', e.g. 'Full-Time'. Kept under Lever's own name because the values are source-specific: Ashby says 'FullTime' and Workable 'Full-time' for the same thing. Mapping to one vocabulary happens downstream."),
    workplace_type STRING OPTIONS(description="Remoteness as published, from 'workplaceType': one of 'remote', 'on-site', 'hybrid', 'unspecified'. Stored verbatim; mapping to the canonical four-value enum happens downstream. Greenhouse has no equivalent field at all."),
    country STRING OPTIONS(description="Country as published, from 'country', an ISO-3166 alpha-2 code in observed data (e.g. 'US', 'CA', 'PL'). Not validated here: other sources use other vocabularies (Ashby sends 'USA')."),
    content STRING OPTIONS(description="Main job description as published, from 'description' (identical to 'descriptionBody' in observed data). HTML, stored unparsed. Lever splits its text across several fields - 'opening', 'additional' and the '...Plain' text twins of each - and only this one is flattened; the rest stay in 'raw'. Assembling the full text is a downstream decision."),
    additional STRING OPTIONS(description="Secondary description section as published, from 'additional' (benefits, EEO statements). HTML, stored unparsed. Roughly 60% the size of 'content' in observed data: dropping it loses a third of the posting's text, which is why it is a column and not left in 'raw'."),
    salary_min NUMERIC OPTIONS(description="Lower bound of the advertised salary, from 'salaryRange.min'. NUMERIC, not INT64: money must not be stored as a float, and some sources publish decimals. Null when the posting advertises no range - most do not."),
    salary_max NUMERIC OPTIONS(description="Upper bound of the advertised salary, from 'salaryRange.max'."),
    salary_currency STRING OPTIONS(description="Currency of the advertised salary, from 'salaryRange.currency', an ISO-4217 code (e.g. 'USD')."),
    salary_interval STRING OPTIONS(description="Period the salary refers to, from 'salaryRange.interval', e.g. 'per-year-salary'. Without it the amounts are meaningless: 350000 could be annual or a day rate."),
    published_at TIMESTAMP OPTIONS(description="When the posting was published, as reported by the source ('createdAt'). Lever sends epoch MILLISECONDS, not an ISO string as Greenhouse does; the conversion happens in the loader, so the value here is already a real timestamp. A source timestamp, not a pipeline one."),
    raw STRING NOT NULL OPTIONS(description="The complete original API object for this posting, as JSON text. Kept so any field dropped or flattened above - 'allLocations', 'lists', the plain-text twins, 'opening' - can be recovered without re-fetching."),
    company_slug STRING OPTIONS(description="The board this row's file was fetched from (the slug in the landed file's path). Stamped by the loader; the MERGE copies it to the raw table. See the raw table's company_slug."),
    first_seen_at TIMESTAMP NOT NULL OPTIONS(description="Landing time of the file this row came from. In staging it equals landed_at and last_seen_at; the MERGE decides what reaches the final table, where it means something different (the FIRST sighting ever)."),
    last_seen_at TIMESTAMP NOT NULL OPTIONS(description="Landing time of the file this row came from. Compared against the final table's last_seen_at by the MERGE, so older files cannot overwrite newer rows."),
    landed_at TIMESTAMP NOT NULL OPTIONS(description="When the GCS file this row came from was created (the object's time_created). Ties every row back to one landed file: used to deduplicate (newest file wins per id) and by the C2 check to prove staging was rebuilt from this day's files."),
    PRIMARY KEY (id, landed_at) NOT ENFORCED
)
OPTIONS(description="One row per Lever job posting PER LANDED FILE (so the same id appears once per file that contained it). Load-mechanics staging only: fully replaced (WRITE_TRUNCATE) on every run of the lever_ingestion DAG and then MERGEd into dev_raw.lever_postings. Not partitioned: it holds one run's data, is rebuilt from scratch each time and is always scanned whole by the MERGE, so there is nothing for partition pruning to skip. Not the dbt staging layer - unrelated concept, same word.");
